import React, { useState, useEffect } from 'react';
import { api } from '../../services/api';
import type {
  APICheckTarget,
  CreateAPICheckTargetData,
  HTTPMethod,
  APITestRequestResult,
} from '../../types/api_checks';
import {
  X,
  Loader2,
  Plug,
  Code2,
  CheckCircle2,
  Lock,
  User,
  Key,
  Plus,
  Trash2,
  KeyRound,
  AlertTriangle,
  Zap,
  Check,
  Sparkles,
  ArrowRight,
  Clock,
  Database,
  Layers,
} from 'lucide-react';

interface APICheckFormProps {
  target?: APICheckTarget | null;
  onSubmit: (data: CreateAPICheckTargetData) => Promise<void>;
  onClose: () => void;
}

type AuthType = 'none' | 'basic' | 'bearer' | 'apikey';
type BodyMode = 'kv' | 'raw';
type SchemaMode = 'builder' | 'raw';

const HTTP_METHODS: HTTPMethod[] = ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'HEAD'];

interface KeyValuePair {
  key: string;
  value: string;
}

interface SchemaFieldPair {
  field: string;
  type: 'string' | 'integer' | 'float' | 'boolean' | 'list' | 'dict';
}

export default function APICheckForm({ target, onSubmit, onClose }: APICheckFormProps) {
  const [activeTab, setActiveTab] = useState<'auth' | 'body' | 'schema'>('auth');
  const [name, setName] = useState('');
  const [url, setUrl] = useState('');
  const [method, setMethod] = useState<HTTPMethod>('GET');
  const [expectedStatus, setExpectedStatus] = useState<number>(200);
  const [expectedTimeMs, setExpectedTimeMs] = useState<number>(2000);
  const [checkInterval, setCheckInterval] = useState<number>(60);
  const [enabled, setEnabled] = useState<boolean>(true);

  // Authentication states
  const [authType, setAuthType] = useState<AuthType>('none');
  const [authUser, setAuthUser] = useState('');
  const [authPass, setAuthPass] = useState('');
  const [authToken, setAuthToken] = useState('');
  const [apiKeyHeader, setApiKeyHeader] = useState('X-API-Key');
  const [apiKeyValue, setApiKeyValue] = useState('');

  // Body states
  const [bodyMode, setBodyMode] = useState<BodyMode>('kv');
  const [bodyPairs, setBodyPairs] = useState<KeyValuePair[]>([{ key: '', value: '' }]);
  const [requestBodyJson, setRequestBodyJson] = useState('');

  // Schema states
  const [schemaMode, setSchemaMode] = useState<SchemaMode>('builder');
  const [schemaFields, setSchemaFields] = useState<SchemaFieldPair[]>([
    { field: '', type: 'string' },
  ]);
  const [expectedSchemaJson, setExpectedSchemaJson] = useState('');

  // Live Test states
  const [isTesting, setIsTesting] = useState(false);
  const [testResult, setTestResult] = useState<APITestRequestResult | null>(null);
  const [schemaAutoGenerated, setSchemaAutoGenerated] = useState(false);

  const [jsonError, setJsonError] = useState<string | null>(null);
  const [submitting, setSubmitting] = useState(false);

  // Populate data if editing
  useEffect(() => {
    if (target) {
      setName(target.name || '');
      setUrl(target.url || '');
      setMethod((target.method as HTTPMethod) || 'GET');
      setExpectedStatus(target.expected_status || 200);
      setExpectedTimeMs(target.expected_response_time_ms || 2000);
      setCheckInterval(target.check_interval || 60);
      setEnabled(target.enabled ?? true);

      // Parse Auth from request_headers
      const headers = target.request_headers || {};
      const authHeader = headers['Authorization'] || headers['authorization'] || '';
      if (authHeader.startsWith('Basic ')) {
        setAuthType('basic');
        try {
          const decoded = atob(authHeader.replace('Basic ', ''));
          const [u, p] = decoded.split(':');
          setAuthUser(u || '');
          setAuthPass(p || '');
        } catch {
          // keep empty
        }
      } else if (authHeader.startsWith('Bearer ')) {
        setAuthType('bearer');
        setAuthToken(authHeader.replace('Bearer ', ''));
      } else {
        const apiKeyEntry = Object.entries(headers).find(
          ([k]) =>
            k.toLowerCase() === 'x-api-key' ||
            k.toLowerCase() === 'apikey' ||
            k.toLowerCase() === 'api-key'
        );
        if (apiKeyEntry) {
          setAuthType('apikey');
          setApiKeyHeader(apiKeyEntry[0]);
          setApiKeyValue(apiKeyEntry[1]);
        } else {
          setAuthType('none');
        }
      }

      // Parse Body
      const body = target.request_body;
      if (body && typeof body === 'object' && Object.keys(body).length > 0) {
        setBodyMode('raw');
        setRequestBodyJson(JSON.stringify(body, null, 2));
      } else {
        setBodyMode('kv');
        setBodyPairs([{ key: '', value: '' }]);
      }

      // Parse Schema
      const schema = target.expected_schema;
      if (schema && typeof schema === 'object' && Object.keys(schema).length > 0) {
        const fields = Object.entries(schema).map(([field, type]) => ({
          field,
          type: (type as any) || 'string',
        }));
        setSchemaFields(fields.length > 0 ? fields : [{ field: '', type: 'string' }]);
        setExpectedSchemaJson(JSON.stringify(schema, null, 2));
      } else {
        setSchemaFields([{ field: '', type: 'string' }]);
        setExpectedSchemaJson('');
      }
    } else {
      setName('');
      setUrl('');
      setMethod('GET');
      setExpectedStatus(200);
      setExpectedTimeMs(2000);
      setEnabled(true);
      setAuthType('none');
      setAuthUser('');
      setAuthPass('');
      setAuthToken('');
      setApiKeyHeader('X-API-Key');
      setApiKeyValue('');
      setBodyMode('kv');
      setBodyPairs([{ key: '', value: '' }]);
      setRequestBodyJson('');
      setSchemaMode('builder');
      setSchemaFields([{ field: '', type: 'string' }]);
      setExpectedSchemaJson('');
      setTestResult(null);
    }
  }, [target]);

  // Body Pair handlers
  const addBodyPair = () => setBodyPairs([...bodyPairs, { key: '', value: '' }]);
  const removeBodyPair = (index: number) => setBodyPairs(bodyPairs.filter((_, i) => i !== index));
  const updateBodyPair = (index: number, field: 'key' | 'value', val: string) => {
    const updated = [...bodyPairs];
    updated[index][field] = val;
    setBodyPairs(updated);
  };

  // Schema Field handlers
  const addSchemaField = () => setSchemaFields([...schemaFields, { field: '', type: 'string' }]);
  const removeSchemaField = (index: number) =>
    setSchemaFields(schemaFields.filter((_, i) => i !== index));
  const updateSchemaField = (index: number, key: 'field' | 'type', val: any) => {
    const updated = [...schemaFields];
    updated[index][key] = val;
    setSchemaFields(updated);
  };

  // Live Test Execution Handler
  const handleTestRequest = async () => {
    if (!url.trim()) return;
    setIsTesting(true);
    setTestResult(null);
    setSchemaAutoGenerated(false);

    // Build headers from Auth tab
    const headers: Record<string, string> = {};
    if (authType === 'basic' && authUser.trim()) {
      const token = btoa(`${authUser.trim()}:${authPass}`);
      headers['Authorization'] = `Basic ${token}`;
    } else if (authType === 'bearer' && authToken.trim()) {
      headers['Authorization'] = `Bearer ${authToken.trim()}`;
    } else if (authType === 'apikey' && apiKeyHeader.trim() && apiKeyValue.trim()) {
      headers[apiKeyHeader.trim()] = apiKeyValue.trim();
    }

    // Build body
    let body: Record<string, any> = {};
    if (method !== 'GET' && method !== 'HEAD') {
      if (bodyMode === 'kv') {
        bodyPairs.forEach((pair) => {
          if (pair.key.trim()) {
            let parsedVal: any = pair.value.trim();
            if (parsedVal === 'true') parsedVal = true;
            else if (parsedVal === 'false') parsedVal = false;
            else if (!isNaN(Number(parsedVal)) && parsedVal !== '') parsedVal = Number(parsedVal);
            body[pair.key.trim()] = parsedVal;
          }
        });
      } else if (requestBodyJson.trim()) {
        try {
          body = JSON.parse(requestBodyJson);
        } catch {
          // ignore or empty
        }
      }
    }

    try {
      const response = await api.post('api-checks/test-request/', {
        url: url.trim(),
        method,
        headers,
        body,
      });
      setTestResult(response.data?.data as APITestRequestResult);
    } catch (err: any) {
      setTestResult({
        success: false,
        status_code: err.response?.data?.data?.status_code || null,
        response_time_ms: null,
        headers: {},
        body: null,
        is_json: false,
        size_bytes: 0,
        error:
          err.response?.data?.message || err.message || 'Error al conectar con el endpoint remoto.',
      });
    } finally {
      setIsTesting(false);
    }
  };

  // Auto-generate JSON Schema from response
  const handleAutoGenerateSchema = () => {
    if (!testResult) return;

    if (testResult.schema_inferred && Object.keys(testResult.schema_inferred).length > 0) {
      const entries = Object.entries(testResult.schema_inferred);
      const fields: SchemaFieldPair[] = entries.map(([field, type]) => ({
        field,
        type: (type as any) || 'string',
      }));
      setSchemaFields(fields);
      setExpectedSchemaJson(JSON.stringify(testResult.schema_inferred, null, 2));
    }

    if (testResult.status_code) {
      setExpectedStatus(testResult.status_code);
    }
    if (testResult.response_time_ms) {
      setExpectedTimeMs(Math.max(Math.round(testResult.response_time_ms * 2), 500));
    }

    setSchemaAutoGenerated(true);
    setActiveTab('schema');
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setJsonError(null);
    if (!name.trim() || !url.trim()) return;

    // 1. Build Headers
    const headers: Record<string, string> = {};
    if (authType === 'basic' && authUser.trim()) {
      const token = btoa(`${authUser.trim()}:${authPass}`);
      headers['Authorization'] = `Basic ${token}`;
    } else if (authType === 'bearer' && authToken.trim()) {
      headers['Authorization'] = `Bearer ${authToken.trim()}`;
    } else if (authType === 'apikey' && apiKeyHeader.trim() && apiKeyValue.trim()) {
      headers[apiKeyHeader.trim()] = apiKeyValue.trim();
    }

    // 2. Build Request Body
    let body: Record<string, any> = {};
    if (method !== 'GET' && method !== 'HEAD') {
      if (bodyMode === 'kv') {
        bodyPairs.forEach((pair) => {
          if (pair.key.trim()) {
            let parsedVal: any = pair.value.trim();
            if (parsedVal === 'true') parsedVal = true;
            else if (parsedVal === 'false') parsedVal = false;
            else if (!isNaN(Number(parsedVal)) && parsedVal !== '') parsedVal = Number(parsedVal);
            body[pair.key.trim()] = parsedVal;
          }
        });
      } else if (requestBodyJson.trim()) {
        try {
          body = JSON.parse(requestBodyJson);
        } catch {
          setJsonError(
            'El campo "Cuerpo de Petición (Body JSON)" no contiene un formato JSON válido.'
          );
          return;
        }
      }
    }

    // 3. Build Expected Schema
    let schema: Record<string, string> = {};
    if (schemaMode === 'builder') {
      schemaFields.forEach((item) => {
        if (item.field.trim()) {
          schema[item.field.trim()] = item.type;
        }
      });
    } else if (expectedSchemaJson.trim()) {
      try {
        schema = JSON.parse(expectedSchemaJson);
      } catch {
        setJsonError('El campo "Esquema Esperado JSON" no contiene un formato JSON válido.');
        return;
      }
    }

    setSubmitting(true);
    try {
      await onSubmit({
        name: name.trim(),
        url: url.trim(),
        method,
        expected_status: Number(expectedStatus),
        expected_response_time_ms: Number(expectedTimeMs),
        check_interval: Number(checkInterval),
        enabled,
        request_headers: headers,
        request_body: body,
        expected_schema: schema,
      });
      onClose();
    } finally {
      setSubmitting(false);
    }
  };

  return (
    <div
      className="fixed inset-0 bg-black/70 backdrop-blur-xs flex items-center justify-center z-50 p-4 animate-in fade-in duration-200"
      onClick={onClose}
    >
      <div
        className="bg-bg-card border border-border-base rounded-3xl p-6 sm:p-8 w-full max-w-2xl max-h-[92vh] overflow-y-auto shadow-2xl"
        onClick={(e) => e.stopPropagation()}
      >
        <div className="flex items-center justify-between mb-5 border-b border-border-base/70 pb-4">
          <h2 className="text-xl font-bold text-text-main flex items-center gap-2 font-sans">
            <Plug size={22} className="text-accent-green" />
            {target ? 'Editar API Check Target' : 'Nuevo API Check Target'}
          </h2>
          <button
            onClick={onClose}
            className="text-text-muted hover:text-text-main transition-colors p-1"
          >
            <X size={20} />
          </button>
        </div>

        {jsonError && (
          <div className="mb-4 p-3.5 bg-accent-red/10 border border-accent-red/30 rounded-2xl text-accent-red text-xs flex items-center gap-2">
            <AlertTriangle size={16} className="shrink-0" />
            <span>{jsonError}</span>
          </div>
        )}

        <form onSubmit={handleSubmit} className="space-y-5">
          {/* Main Config */}
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <div>
              <label className="block text-xs font-semibold text-text-muted mb-1.5">
                Nombre del Servicio / API
              </label>
              <input
                type="text"
                required
                placeholder="ej. Micoope en Línea / Auth API"
                value={name}
                onChange={(e) => setName(e.target.value)}
                className="w-full bg-bg-dark border border-border-base rounded-xl px-4 py-2.5 text-sm text-text-main placeholder:text-text-dim focus:outline-none focus:border-accent-green"
              />
            </div>

            <div>
              <label className="block text-xs font-semibold text-text-muted mb-1.5">
                Método HTTP
              </label>
              <select
                value={method}
                onChange={(e) => {
                  setMethod(e.target.value as HTTPMethod);
                  setTestResult(null);
                }}
                className="w-full bg-bg-dark border border-border-base rounded-xl px-3 py-2.5 text-sm text-text-main focus:outline-none focus:border-accent-green font-mono font-bold cursor-pointer"
              >
                {HTTP_METHODS.map((m) => (
                  <option key={m} value={m}>
                    {m}
                  </option>
                ))}
              </select>
            </div>
          </div>

          <div>
            <div className="flex items-center justify-between mb-1.5">
              <label className="text-xs font-semibold text-text-muted">
                URL del Endpoint REST
              </label>
              <span className="text-[11px] text-text-dim">Protocolo HTTP o HTTPS</span>
            </div>
            <div className="flex flex-col sm:flex-row gap-2">
              <input
                type="url"
                required
                placeholder="ej. https://api.micoope.com.gt/v1/health"
                value={url}
                onChange={(e) => {
                  setUrl(e.target.value);
                  setTestResult(null);
                }}
                className="flex-1 bg-bg-dark border border-border-base rounded-xl px-4 py-2.5 text-sm text-text-main placeholder:text-text-dim focus:outline-none focus:border-accent-green font-mono"
              />
              <button
                type="button"
                onClick={handleTestRequest}
                disabled={!url.trim() || isTesting}
                className="px-4 py-2.5 bg-accent-green/10 border border-accent-green/30 text-accent-green hover:bg-accent-green hover:text-black font-semibold rounded-xl text-xs flex items-center justify-center gap-1.5 transition-all disabled:opacity-50 shrink-0 cursor-pointer shadow-sm"
                title="Ejecutar prueba HTTP instantánea estilo Postman"
              >
                {isTesting ? (
                  <>
                    <Loader2 className="animate-spin" size={15} />
                    <span>Probando...</span>
                  </>
                ) : (
                  <>
                    <Zap size={15} className="text-accent-yellow" />
                    <span>Probar en Vivo</span>
                  </>
                )}
              </button>
            </div>
          </div>

          {/* LIVE TEST RESPONSE VIEWER (Postman-style preview) */}
          {testResult && (
            <div
              className={`p-4 rounded-2xl border text-xs animate-in fade-in duration-200 ${
                testResult.success
                  ? testResult.status_code && testResult.status_code < 400
                    ? 'bg-accent-green/5 border-accent-green/30'
                    : 'bg-accent-yellow/5 border-accent-yellow/30'
                  : 'bg-accent-red/5 border-accent-red/30'
              }`}
            >
              <div className="flex flex-wrap items-center justify-between gap-2 pb-2.5 border-b border-border-base/50">
                <div className="flex items-center gap-2">
                  <span className="font-bold text-text-main flex items-center gap-1.5">
                    {testResult.success ? (
                      <CheckCircle2 size={15} className="text-accent-green" />
                    ) : (
                      <AlertTriangle size={15} className="text-accent-red" />
                    )}
                    Respuesta del Endpoint:
                  </span>
                  {testResult.status_code && (
                    <span
                      className={`px-2.5 py-0.5 rounded-full font-mono font-bold text-[11px] ${
                        testResult.status_code < 300
                          ? 'bg-accent-green/15 text-accent-green border border-accent-green/30'
                          : testResult.status_code < 400
                          ? 'bg-accent-blue/15 text-accent-blue border border-accent-blue/30'
                          : 'bg-accent-red/15 text-accent-red border border-accent-red/30'
                      }`}
                    >
                      HTTP {testResult.status_code}
                    </span>
                  )}
                  {testResult.response_time_ms !== null && (
                    <span className="px-2 py-0.5 rounded-full font-mono text-[11px] bg-bg-dark text-text-muted border border-border-base flex items-center gap-1">
                      <Clock size={11} />
                      {testResult.response_time_ms} ms
                    </span>
                  )}
                </div>

                {/* Auto-generate Schema Button */}
                {testResult.success && (
                  <button
                    type="button"
                    onClick={handleAutoGenerateSchema}
                    className="flex items-center gap-1 px-3 py-1 bg-accent-green/15 border border-accent-green/40 text-accent-green hover:bg-accent-green hover:text-black rounded-full font-bold text-[11px] transition-all cursor-pointer shadow-xs"
                    title="Ajustar parámetros y schema automáticamente con esta respuesta"
                  >
                    <Sparkles size={12} />
                    <span>
                      {schemaAutoGenerated ? 'Schema Aplicado' : 'Auto-generar Config & Schema'}
                    </span>
                  </button>
                )}
              </div>

              {/* Response Body Inspector */}
              <div className="mt-2.5">
                <div className="text-[11px] text-text-dim mb-1 font-mono flex items-center justify-between">
                  <span>Cuerpo de Respuesta {testResult.is_json ? '(JSON)' : '(Texto)'}:</span>
                  <span>{testResult.size_bytes} bytes</span>
                </div>
                <pre className="p-3 bg-bg-dark rounded-xl border border-border-base/70 font-mono text-[11px] text-text-main max-h-36 overflow-y-auto whitespace-pre-wrap break-all leading-relaxed">
                  {testResult.success
                    ? typeof testResult.body === 'object'
                      ? JSON.stringify(testResult.body, null, 2)
                      : String(testResult.body || 'Sin contenido en la respuesta.')
                    : testResult.error}
                </pre>
              </div>
            </div>
          )}

          {/* Thresholds */}
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
            <div>
              <label className="block text-xs font-semibold text-text-muted mb-1.5">
                Status Esperado
              </label>
              <input
                type="number"
                required
                min={100}
                max={599}
                value={expectedStatus}
                onChange={(e) => setExpectedStatus(Number(e.target.value))}
                className="w-full bg-bg-dark border border-border-base rounded-xl px-3 py-2.5 text-sm text-text-main focus:outline-none focus:border-accent-green font-mono"
              />
            </div>

            <div>
              <label className="block text-xs font-semibold text-text-muted mb-1.5">
                Max Latencia (ms)
              </label>
              <input
                type="number"
                required
                min={10}
                max={30000}
                step={1}
                value={expectedTimeMs}
                onChange={(e) => setExpectedTimeMs(Number(e.target.value))}
                className="w-full bg-bg-dark border border-border-base rounded-xl px-3 py-2.5 text-sm text-text-main focus:outline-none focus:border-accent-green font-mono"
              />
            </div>

            <div>
              <label className="block text-xs font-semibold text-text-muted mb-1.5">
                Frecuencia de Check
              </label>
              <select
                value={checkInterval}
                onChange={(e) => setCheckInterval(Number(e.target.value))}
                className="w-full bg-bg-dark border border-border-base rounded-xl px-3 py-2.5 text-sm text-text-main focus:outline-none focus:border-accent-green font-mono cursor-pointer"
              >
                <option value={30}>Cada 30 seg</option>
                <option value={60}>Cada 1 min</option>
                <option value={120}>Cada 2 min</option>
                <option value={300}>Cada 5 min</option>
              </select>
            </div>
          </div>

          {/* Advanced Configuration Tabs */}
          <div className="border border-border-base/70 rounded-2xl p-4 bg-bg-dark/40 space-y-4">
            <div className="flex border-b border-border-base/60 gap-4 text-xs font-medium pb-2">
              <button
                type="button"
                onClick={() => setActiveTab('auth')}
                className={`pb-2 transition-colors flex items-center gap-1.5 cursor-pointer ${
                  activeTab === 'auth'
                    ? 'border-b-2 border-accent-green text-accent-green font-bold'
                    : 'text-text-dim hover:text-text-main'
                }`}
              >
                <Lock size={14} />
                Autenticación & Tokens
              </button>

              {method !== 'GET' && method !== 'HEAD' && (
                <button
                  type="button"
                  onClick={() => setActiveTab('body')}
                  className={`pb-2 transition-colors flex items-center gap-1.5 cursor-pointer ${
                    activeTab === 'body'
                      ? 'border-b-2 border-accent-green text-accent-green font-bold'
                      : 'text-text-dim hover:text-text-main'
                  }`}
                >
                  <Code2 size={14} />
                  Cuerpo (Body Payload)
                </button>
              )}

              <button
                type="button"
                onClick={() => setActiveTab('schema')}
                className={`pb-2 transition-colors flex items-center gap-1.5 cursor-pointer ${
                  activeTab === 'schema'
                    ? 'border-b-2 border-accent-green text-accent-green font-bold'
                    : 'text-text-dim hover:text-text-main'
                }`}
              >
                <CheckCircle2 size={14} />
                Validación de Schema
                {schemaFields.some((f) => f.field.trim()) && (
                  <span className="w-2 h-2 rounded-full bg-accent-green" />
                )}
              </button>
            </div>

            {/* TAB 1: AUTHENTICATION */}
            {activeTab === 'auth' && (
              <div className="space-y-4 pt-1">
                <div className="flex gap-2">
                  {[
                    { id: 'none', label: 'Sin Auth' },
                    { id: 'basic', label: 'Basic Auth' },
                    { id: 'bearer', label: 'Bearer Token' },
                    { id: 'apikey', label: 'API Key' },
                  ].map((item) => (
                    <button
                      key={item.id}
                      type="button"
                      onClick={() => setAuthType(item.id as AuthType)}
                      className={`px-3 py-1.5 rounded-xl border text-xs font-semibold transition-all cursor-pointer ${
                        authType === item.id
                          ? 'bg-accent-green/10 border-accent-green/40 text-accent-green'
                          : 'bg-bg-dark border-border-base text-text-dim hover:text-text-main'
                      }`}
                    >
                      {item.label}
                    </button>
                  ))}
                </div>

                {authType === 'basic' && (
                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 pt-2">
                    <div>
                      <label className="block text-[11px] text-text-dim mb-1">Usuario / Email</label>
                      <input
                        type="text"
                        placeholder="usuario@empresa.com"
                        value={authUser}
                        onChange={(e) => setAuthUser(e.target.value)}
                        className="w-full bg-bg-card border border-border-base rounded-xl px-3 py-2 text-xs text-text-main focus:outline-none focus:border-accent-green"
                      />
                    </div>
                    <div>
                      <label className="block text-[11px] text-text-dim mb-1">Contraseña</label>
                      <input
                        type="password"
                        placeholder="••••••••"
                        value={authPass}
                        onChange={(e) => setAuthPass(e.target.value)}
                        className="w-full bg-bg-card border border-border-base rounded-xl px-3 py-2 text-xs text-text-main focus:outline-none focus:border-accent-green"
                      />
                    </div>
                  </div>
                )}

                {authType === 'bearer' && (
                  <div className="pt-2">
                    <label className="block text-[11px] text-text-dim mb-1">
                      Bearer Token (JWT / API Token)
                    </label>
                    <input
                      type="text"
                      placeholder="eyJhbGciOiJIUzI1NiIsIn..."
                      value={authToken}
                      onChange={(e) => setAuthToken(e.target.value)}
                      className="w-full bg-bg-card border border-border-base rounded-xl px-3 py-2 text-xs text-text-main font-mono focus:outline-none focus:border-accent-green"
                    />
                  </div>
                )}

                {authType === 'apikey' && (
                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 pt-2">
                    <div>
                      <label className="block text-[11px] text-text-dim mb-1">Nombre del Header</label>
                      <input
                        type="text"
                        placeholder="X-API-Key"
                        value={apiKeyHeader}
                        onChange={(e) => setApiKeyHeader(e.target.value)}
                        className="w-full bg-bg-card border border-border-base rounded-xl px-3 py-2 text-xs text-text-main font-mono focus:outline-none focus:border-accent-green"
                      />
                    </div>
                    <div>
                      <label className="block text-[11px] text-text-dim mb-1">Valor de la Llave</label>
                      <input
                        type="password"
                        placeholder="sk_live_..."
                        value={apiKeyValue}
                        onChange={(e) => setApiKeyValue(e.target.value)}
                        className="w-full bg-bg-card border border-border-base rounded-xl px-3 py-2 text-xs text-text-main font-mono focus:outline-none focus:border-accent-green"
                      />
                    </div>
                  </div>
                )}
              </div>
            )}

            {/* TAB 2: REQUEST BODY */}
            {activeTab === 'body' && method !== 'GET' && method !== 'HEAD' && (
              <div className="space-y-4 pt-1">
                <div className="flex gap-2">
                  <button
                    type="button"
                    onClick={() => setBodyMode('kv')}
                    className={`px-3 py-1.5 rounded-xl border text-xs font-semibold cursor-pointer ${
                      bodyMode === 'kv'
                        ? 'bg-accent-green/10 border-accent-green/40 text-accent-green'
                        : 'bg-bg-dark border-border-base text-text-dim'
                    }`}
                  >
                    Clave - Valor
                  </button>
                  <button
                    type="button"
                    onClick={() => setBodyMode('raw')}
                    className={`px-3 py-1.5 rounded-xl border text-xs font-semibold cursor-pointer ${
                      bodyMode === 'raw'
                        ? 'bg-accent-green/10 border-accent-green/40 text-accent-green'
                        : 'bg-bg-dark border-border-base text-text-dim'
                    }`}
                  >
                    JSON Raw
                  </button>
                </div>

                {bodyMode === 'kv' ? (
                  <div className="space-y-2">
                    {bodyPairs.map((pair, idx) => (
                      <div key={idx} className="flex gap-2 items-center">
                        <input
                          type="text"
                          placeholder="Clave (ej. usuario)"
                          value={pair.key}
                          onChange={(e) => updateBodyPair(idx, 'key', e.target.value)}
                          className="flex-1 bg-bg-card border border-border-base rounded-xl px-3 py-1.5 text-xs text-text-main font-mono"
                        />
                        <input
                          type="text"
                          placeholder="Valor"
                          value={pair.value}
                          onChange={(e) => updateBodyPair(idx, 'value', e.target.value)}
                          className="flex-1 bg-bg-card border border-border-base rounded-xl px-3 py-1.5 text-xs text-text-main font-mono"
                        />
                        {bodyPairs.length > 1 && (
                          <button
                            type="button"
                            onClick={() => removeBodyPair(idx)}
                            className="p-1.5 text-accent-red hover:bg-accent-red/10 rounded-lg transition-colors cursor-pointer"
                          >
                            <Trash2 size={14} />
                          </button>
                        )}
                      </div>
                    ))}
                    <button
                      type="button"
                      onClick={addBodyPair}
                      className="flex items-center gap-1.5 text-xs font-mono text-accent-green hover:underline pt-1 cursor-pointer"
                    >
                      <Plus size={14} />
                      + Agregar Par Clave-Valor
                    </button>
                  </div>
                ) : (
                  <div>
                    <textarea
                      rows={4}
                      placeholder='{\n  "query": "status",\n  "active": true\n}'
                      value={requestBodyJson}
                      onChange={(e) => setRequestBodyJson(e.target.value)}
                      className="w-full bg-bg-card border border-border-base rounded-xl p-3 text-xs font-mono text-text-main focus:outline-none focus:border-accent-green"
                    />
                  </div>
                )}
              </div>
            )}

            {/* TAB 3: SCHEMA VALIDATION */}
            {activeTab === 'schema' && (
              <div className="space-y-4 pt-1">
                <div className="flex items-center justify-between">
                  <div className="flex gap-2">
                    <button
                      type="button"
                      onClick={() => setSchemaMode('builder')}
                      className={`px-3 py-1.5 rounded-xl border text-xs font-semibold cursor-pointer ${
                        schemaMode === 'builder'
                          ? 'bg-accent-green/10 border-accent-green/40 text-accent-green'
                          : 'bg-bg-dark border-border-base text-text-dim'
                      }`}
                    >
                      Constructor Visual
                    </button>
                    <button
                      type="button"
                      onClick={() => setSchemaMode('raw')}
                      className={`px-3 py-1.5 rounded-xl border text-xs font-semibold cursor-pointer ${
                        schemaMode === 'raw'
                          ? 'bg-accent-green/10 border-accent-green/40 text-accent-green'
                          : 'bg-bg-dark border-border-base text-text-dim'
                      }`}
                    >
                      JSON Raw
                    </button>
                  </div>

                  {testResult && testResult.schema_inferred && (
                    <button
                      type="button"
                      onClick={handleAutoGenerateSchema}
                      className="text-xs text-accent-green hover:underline flex items-center gap-1 font-semibold cursor-pointer"
                    >
                      <Sparkles size={13} />
                      Auto-poblar desde Test
                    </button>
                  )}
                </div>

                {schemaMode === 'builder' ? (
                  <div className="space-y-2">
                    {schemaFields.map((item, idx) => (
                      <div key={idx} className="flex gap-2 items-center">
                        <input
                          type="text"
                          placeholder="Nombre del campo (ej. status, id, data)"
                          value={item.field}
                          onChange={(e) => updateSchemaField(idx, 'field', e.target.value)}
                          className="flex-1 bg-bg-card border border-border-base rounded-xl px-3 py-1.5 text-xs text-text-main font-mono"
                        />
                        <select
                          value={item.type}
                          onChange={(e) => updateSchemaField(idx, 'type', e.target.value)}
                          className="w-36 bg-bg-card border border-border-base rounded-xl px-3 py-1.5 text-xs text-text-main font-mono cursor-pointer"
                        >
                          <option value="string">Cadena (string)</option>
                          <option value="integer">Entero (integer)</option>
                          <option value="float">Decimal (float)</option>
                          <option value="boolean">Booleano (boolean)</option>
                          <option value="list">Lista / Array (list)</option>
                          <option value="dict">Objeto (dict)</option>
                        </select>
                        {schemaFields.length > 1 && (
                          <button
                            type="button"
                            onClick={() => removeSchemaField(idx)}
                            className="p-1.5 text-accent-red hover:bg-accent-red/10 rounded-lg transition-colors cursor-pointer"
                          >
                            <Trash2 size={14} />
                          </button>
                        )}
                      </div>
                    ))}

                    <button
                      type="button"
                      onClick={addSchemaField}
                      className="flex items-center gap-1.5 text-xs font-mono text-accent-green hover:underline pt-1 cursor-pointer"
                    >
                      <Plus size={14} />
                      + Agregar Campo a Validar
                    </button>
                  </div>
                ) : (
                  <div>
                    <textarea
                      rows={4}
                      placeholder='{\n  "status": "string",\n  "id": "integer"\n}'
                      value={expectedSchemaJson}
                      onChange={(e) => setExpectedSchemaJson(e.target.value)}
                      className="w-full bg-bg-card border border-border-base rounded-xl p-3 text-xs font-mono text-text-main focus:outline-none focus:border-accent-green"
                    />
                  </div>
                )}
              </div>
            )}
          </div>

          <div className="flex items-center gap-3 pt-1">
            <input
              type="checkbox"
              id="enabledCheck"
              checked={enabled}
              onChange={(e) => setEnabled(e.target.checked)}
              className="w-4 h-4 rounded bg-bg-dark border-border-base text-accent-green focus:ring-accent-green focus:ring-offset-bg-dark cursor-pointer"
            />
            <label
              htmlFor="enabledCheck"
              className="text-sm font-medium text-text-main cursor-pointer"
            >
              Monitoreo Activo en Celery Beat
            </label>
          </div>

          <div className="flex gap-3 pt-4 border-t border-border-base">
            <button
              type="button"
              onClick={onClose}
              className="flex-1 py-2.5 border border-border-base rounded-full text-sm text-text-muted hover:bg-bg-dark transition-colors cursor-pointer"
            >
              Cancelar
            </button>
            <button
              type="submit"
              disabled={submitting}
              className="flex-1 py-2.5 bg-accent-green text-black font-semibold rounded-full text-sm hover:opacity-90 transition-opacity flex items-center justify-center gap-2 disabled:opacity-50 shadow-sm cursor-pointer"
            >
              {submitting ? (
                <Loader2 className="animate-spin" size={18} />
              ) : target ? (
                'Actualizar'
              ) : (
                'Guardar y Monitorear'
              )}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
}
