# Generated by Django 5.1.15 on 2026-09-04 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_apitoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='apitoken',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apitoken',
            name='scope',
            field=models.CharField(choices=[('read', 'Read Only'), ('full', 'Full Access')], default='full', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='notification_preferences',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='timezone',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
