# Generated by Django 5.2.17 on 2026-10-06 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_seed_private_beta'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisposableDomainPolicy',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('version', models.CharField(max_length=50)),
                ('domains', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
