# Generated by Django 5.1.15 on 2026-09-03 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dns_monitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dnsrecord',
            name='response_time_ms',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dnsrecord',
            name='record_type',
            field=models.CharField(choices=[('A', 'A'), ('AAAA', 'AAAA'), ('MX', 'MX'), ('TXT', 'TXT'), ('NS', 'NS'), ('CNAME', 'CNAME'), ('SOA', 'SOA'), ('PTR', 'PTR'), ('CAA', 'CAA')], max_length=10),
        ),
    ]
