# Generated by Django 5.1.15 on 2026-07-28 15:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('target_type', models.CharField(choices=[('ssl', 'SSL'), ('monitoring', 'Monitoring'), ('dns', 'DNS'), ('domain', 'Domain'), ('api_check', 'API Check'), ('security_headers', 'Security Headers')], max_length=20)),
                ('condition', models.CharField(choices=[('ssl_expiring', 'SSL Expiring'), ('uptime_below', 'Uptime Below'), ('status_down', 'Status Down'), ('response_time_above', 'Response Time Above'), ('dns_changed', 'DNS Changed'), ('domain_expiring', 'Domain Expiring'), ('security_score_below', 'Security Score Below'), ('api_check_failed', 'API Check Failed')], max_length=30)),
                ('threshold', models.FloatField(default=0, help_text='Threshold value (days, percentage, milliseconds, etc.)')),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('warning', 'Warning'), ('info', 'Info')], default='warning', max_length=20)),
                ('enabled', models.BooleanField(default=True)),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization')),
            ],
            options={
                'db_table': 'alerts_rule',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=500)),
                ('message', models.TextField()),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('warning', 'Warning'), ('info', 'Info')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved')], default='active', max_length=20)),
                ('target_type', models.CharField(blank=True, max_length=20)),
                ('target_id', models.UUIDField(blank=True, null=True)),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='organizations.organization')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='alerts.alertrule')),
            ],
            options={
                'db_table': 'alerts_alert',
                'ordering': ['-triggered_at'],
                'indexes': [models.Index(fields=['organization', '-triggered_at'], name='alerts_aler_organiz_750099_idx'), models.Index(fields=['status'], name='alerts_aler_status_2a92cb_idx'), models.Index(fields=['severity'], name='alerts_aler_severit_202179_idx')],
            },
        ),
    ]
