# Generated by Django 5.1.15 on 2026-08-08 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertrule',
            name='target_id',
            field=models.UUIDField(blank=True, help_text='Specific target ID or None for all targets of this type', null=True),
        ),
    ]
