# Generated by Django 5.1.15 on 2026-09-16 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_enhance_smart_alerts'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='alert',
            new_name='alerts_aler_target__476a19_idx',
            old_name='alerts_target_idx',
        ),
    ]
