# Generated by Django 5.1.15 on 2026-07-28 15:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_type', models.CharField(choices=[('sla', 'SLA'), ('availability', 'Availability'), ('ssl', 'SSL'), ('incidents', 'Incidents'), ('trends', 'Trends'), ('summary', 'Summary')], max_length=20)),
                ('title', models.CharField(max_length=500)),
                ('parameters', models.JSONField(blank=True, default=dict, help_text='Report generation parameters (date range, targets, etc.)')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('data', models.JSONField(blank=True, default=dict, help_text='Generated report data')),
                ('error_message', models.TextField(blank=True)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('period_start', models.DateTimeField(blank=True, null=True)),
                ('period_end', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization')),
            ],
            options={
                'db_table': 'reports_report',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', '-created_at'], name='reports_rep_organiz_54f6c2_idx'), models.Index(fields=['report_type'], name='reports_rep_report__dbb097_idx'), models.Index(fields=['status'], name='reports_rep_status_c732ef_idx')],
            },
        ),
    ]
