# Generated by Django 5.1.15 on 2026-08-09 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationchannel',
            name='channel_type',
            field=models.CharField(choices=[('email', 'Email'), ('slack', 'Slack'), ('teams', 'Microsoft Teams'), ('discord', 'Discord'), ('telegram', 'Telegram'), ('webhook', 'Webhook')], max_length=20),
        ),
    ]
