# Generated by Django 5.1.15 on 2026-09-04 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notificationchannel_channel_type'),
    ]

    operations = [
        # NotificationChannel additions
        migrations.AddField(
            model_name='notificationchannel',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='notificationchannel',
            name='min_severity',
            field=models.CharField(
                choices=[('info', 'Informativo (Todas)'), ('warning', 'Advertencia & Crítica'), ('critical', 'Solo Críticas')],
                default='info',
                help_text='Severidad mínima requerida para despachar a este canal',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='notificationchannel',
            name='subscribed_events',
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Eventos suscritos: alert_triggered, alert_resolved, incident_opened, incident_resolved, maintenance',
            ),
        ),
        migrations.AddField(
            model_name='notificationchannel',
            name='rate_limit_per_hour',
            field=models.PositiveIntegerField(
                default=0,
                help_text='Límite máximo de notificaciones por hora (0 = ilimitado)',
            ),
        ),
        migrations.AddField(
            model_name='notificationchannel',
            name='quiet_hours_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notificationchannel',
            name='quiet_hours_start',
            field=models.CharField(blank=True, default='22:00', max_length=5),
        ),
        migrations.AddField(
            model_name='notificationchannel',
            name='quiet_hours_end',
            field=models.CharField(blank=True, default='08:00', max_length=5),
        ),
        migrations.AddField(
            model_name='notificationchannel',
            name='quiet_hours_critical_override',
            field=models.BooleanField(
                default=True,
                help_text='Permitir que alertas críticas ignoren las horas de silencio',
            ),
        ),
        # Notification additions
        migrations.AddField(
            model_name='notification',
            name='severity',
            field=models.CharField(blank=True, default='info', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='event_type',
            field=models.CharField(blank=True, default='alert_triggered', max_length=50),
        ),
        migrations.AddField(
            model_name='notification',
            name='duration_ms',
            field=models.PositiveIntegerField(
                default=0,
                help_text='Tiempo de respuesta de la API/SMTP en ms',
            ),
        ),
        migrations.AddField(
            model_name='notification',
            name='http_status',
            field=models.PositiveIntegerField(
                blank=True,
                help_text='Código de estado HTTP de respuesta',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='notification',
            name='retry_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
