# Generated by Django 5.1.15 on 2026-09-07 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_invitationtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='alert_flapping_threshold',
            field=models.IntegerField(default=3, help_text='Number of state changes in 15m to trigger flapping alert.'),
        ),
        migrations.AddField(
            model_name='organization',
            name='allowed_ip_ranges',
            field=models.TextField(blank=True, default='', help_text='Comma-separated CIDR/IP blocks allowed to access NOC.'),
        ),
        migrations.AddField(
            model_name='organization',
            name='audit_logs_retention_days',
            field=models.IntegerField(default=365, help_text='Days to retain immutable audit trail logs.'),
        ),
        migrations.AddField(
            model_name='organization',
            name='billing_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='organization',
            name='contact_phone',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='organization',
            name='default_scan_interval_seconds',
            field=models.IntegerField(default=60, help_text='Default interval for monitoring checks in seconds.'),
        ),
        migrations.AddField(
            model_name='organization',
            name='logo_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='organization',
            name='metrics_retention_days',
            field=models.IntegerField(default=90, help_text='Days to retain raw time-series metrics in TimescaleDB.'),
        ),
        migrations.AddField(
            model_name='organization',
            name='plan_tier',
            field=models.CharField(choices=[('free', 'Free / Community'), ('pro', 'Pro / Growth'), ('business', 'Business / NOC'), ('enterprise', 'Enterprise')], default='pro', help_text='Current subscription tier.', max_length=20),
        ),
        migrations.AddField(
            model_name='organization',
            name='require_2fa',
            field=models.BooleanField(default=False, help_text='Enforce two-factor authentication for all operators.'),
        ),
        migrations.AddField(
            model_name='organization',
            name='resolved_incidents_retention_days',
            field=models.IntegerField(default=180, help_text='Days to retain resolved incident history.'),
        ),
        migrations.AddField(
            model_name='organization',
            name='session_timeout_minutes',
            field=models.IntegerField(default=120, help_text='Idle session timeout in minutes.'),
        ),
        migrations.AddField(
            model_name='organization',
            name='sla_target_percentage',
            field=models.DecimalField(decimal_places=2, default=99.9, help_text='Global monthly uptime SLA target percentage.', max_digits=5),
        ),
        migrations.AddField(
            model_name='organization',
            name='subscription_status',
            field=models.CharField(choices=[('trialing', 'Trialing'), ('active', 'Active'), ('past_due', 'Past Due'), ('canceled', 'Canceled')], default='trialing', help_text='Billing subscription status.', max_length=20),
        ),
        migrations.AddField(
            model_name='organization',
            name='tax_id',
            field=models.CharField(blank=True, default='', help_text='Tax / Fiscal ID (RUT, RFC, NIF, CIF).', max_length=50),
        ),
        migrations.AddField(
            model_name='organization',
            name='trial_ends_at',
            field=models.DateTimeField(blank=True, help_text='Expiration timestamp for free trial.', null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='website',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
