# Generated by Django 5.1.15 on 2026-09-16 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_organization_alert_flapping_threshold_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='allowed_ip_ranges',
            field=models.TextField(blank=True, default='', help_text='Comma-separated CIDR/IP blocks allowed to access console.'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='locale',
            field=models.CharField(default='es-GT', max_length=10),
        ),
        migrations.AlterField(
            model_name='organization',
            name='plan_tier',
            field=models.CharField(choices=[('free', 'Free / Community'), ('pro', 'Pro / Growth'), ('business', 'Business'), ('enterprise', 'Enterprise')], default='pro', help_text='Current subscription tier.', max_length=20),
        ),
        migrations.AlterField(
            model_name='organization',
            name='timezone',
            field=models.CharField(default='America/Guatemala', max_length=50),
        ),
    ]
