# Generated by Django 5.2.17 on 2026-10-06 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_free_registration_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='beta_managed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='beta_status',
            field=models.CharField(default='active', max_length=20),
        ),
    ]
