# Generated by Django 5.1.15 on 2026-07-28 15:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('investigating', 'Investigating'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('priority', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization')),
            ],
            options={
                'db_table': 'incidents_incident',
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='IncidentAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alert_id', models.UUIDField()),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_alerts', to='incidents.incident')),
            ],
            options={
                'db_table': 'incidents_incident_alert',
                'ordering': ['-added_at'],
            },
        ),
        migrations.CreateModel(
            name='IncidentTimelineEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('created', 'Created'), ('status_changed', 'Status Changed'), ('priority_changed', 'Priority Changed'), ('alert_added', 'Alert Added'), ('note_added', 'Note Added'), ('resolved', 'Resolved'), ('closed', 'Closed')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('old_value', models.CharField(blank=True, max_length=100)),
                ('new_value', models.CharField(blank=True, max_length=100)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='incidents.incident')),
            ],
            options={
                'db_table': 'incidents_timeline_event',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['organization', '-opened_at'], name='incidents_i_organiz_a850d3_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['status'], name='incidents_i_status_9a4f12_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['priority'], name='incidents_i_priorit_b2c75b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='incidentalert',
            unique_together={('incident', 'alert_id')},
        ),
    ]
