# Generated by Django 5.1.15 on 2026-08-09 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('investigating', 'Investigating'), ('identified', 'Identified'), ('mitigated', 'Mitigated'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20),
        ),
    ]
