# Generated by Django 5.1.15 on 2026-09-04 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0002_alter_incident_status'),
        ('organizations', '0002_invitationtoken'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_incidents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incident',
            name='assigned_to_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='incident',
            name='impacted_service',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='incident',
            name='mitigated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='preventive_actions',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='incident',
            name='resolution_summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='incident',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='root_cause',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='incident',
            name='target_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='target_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='incidenttimelineevent',
            name='actor_name',
            field=models.CharField(blank=True, default='Sistema', max_length=255),
        ),
        migrations.AlterField(
            model_name='incidenttimelineevent',
            name='event_type',
            field=models.CharField(choices=[('created', 'Created'), ('status_changed', 'Status Changed'), ('priority_changed', 'Priority Changed'), ('alert_added', 'Alert Added'), ('note_added', 'Note Added'), ('assigned', 'Assigned'), ('rca_updated', 'RCA Updated'), ('mitigated', 'Mitigated'), ('resolved', 'Resolved'), ('closed', 'Closed')], max_length=30),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['target_type', 'target_id'], name='incidents_i_target__05f747_idx'),
        ),
    ]
