# Generated by Django 5.1.15 on 2026-09-16 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0004_incident_assigned_team_incident_assigned_team_name'),
    ]

    operations = [
        # The index already exists in older installations outside Django's migration state.
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        'CREATE INDEX IF NOT EXISTS incidents_incidentalert_alert_id_idx '
                        'ON incidents_incident_alert (alert_id)'
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name='incidentalert',
                    name='alert_id',
                    field=models.UUIDField(db_index=True),
                ),
            ],
        ),
    ]
