# Generated by Django 5.1.15 on 2026-09-07 15:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_invitationtoken'),
        ('status_page', '0003_scheduledmaintenance_status_page_and_more'),
        ('users', '0003_team_contact_email_team_lead'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceWindow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('scheduled', 'Programado'), ('in_progress', 'En Curso'), ('completed', 'Completado'), ('cancelled', 'Cancelado')], db_index=True, default='scheduled', max_length=20)),
                ('start_time', models.DateTimeField(db_index=True)),
                ('end_time', models.DateTimeField(db_index=True)),
                ('recurrence', models.CharField(choices=[('none', 'Única vez'), ('weekly', 'Semanal'), ('biweekly', 'Quincenal'), ('monthly', 'Mensual')], default='none', max_length=20)),
                ('recurrence_day_of_week', models.IntegerField(blank=True, null=True)),
                ('recurrence_time_start', models.TimeField(blank=True, null=True)),
                ('recurrence_time_end', models.TimeField(blank=True, null=True)),
                ('suppress_notifications', models.BooleanField(default=True, help_text='Silencia despachos a canales externos (Slack, Telegram, Teams, Email).')),
                ('exclude_from_sla', models.BooleanField(default=True, help_text='Excluye el downtime durante este periodo del cálculo de SLA en reportes.')),
                ('publish_to_status_page', models.BooleanField(default=False, help_text='Publica automáticamente este mantenimiento en la Status Page seleccionada.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_maintenance_windows', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization')),
                ('responsible_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_windows', to='users.team')),
                ('responsible_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_maintenance_windows', to=settings.AUTH_USER_MODEL)),
                ('status_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_windows', to='status_page.statuspageconfig')),
            ],
            options={
                'db_table': 'maintenance_windows',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceWindowTarget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_type', models.CharField(choices=[('all', 'Toda la Organización (Global)'), ('monitoring', 'Uptime & Latencia'), ('ssl', 'Certificados SSL'), ('dns', 'Registros DNS'), ('domain', 'Dominios WHOIS'), ('api_check', 'API Endpoints'), ('security_headers', 'Security Headers')], default='monitoring', max_length=30)),
                ('target_id', models.UUIDField(blank=True, null=True)),
                ('target_name', models.CharField(blank=True, max_length=255)),
                ('maintenance_window', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='maintenance.maintenancewindow')),
            ],
            options={
                'db_table': 'maintenance_window_targets',
            },
        ),
        migrations.CreateModel(
            name='MaintenanceWindowUpdate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('status', models.CharField(default='in_progress', max_length=30)),
                ('actor_name', models.CharField(blank=True, max_length=150)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('maintenance_window', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='maintenance.maintenancewindow')),
            ],
            options={
                'db_table': 'maintenance_window_updates',
                'ordering': ['-posted_at'],
            },
        ),
    ]
