# Generated by Django 5.1.15 on 2026-09-07 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
        ('status_page', '0003_scheduledmaintenance_status_page_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancewindow',
            name='status_page_maintenance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operational_windows', to='status_page.scheduledmaintenance'),
        ),
    ]
