# Generated by Django 5.1.15 on 2026-07-28 15:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='APICheckTarget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=500)),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH')], default='GET', max_length=10)),
                ('expected_status', models.IntegerField(default=200)),
                ('expected_response_time_ms', models.IntegerField(default=2000)),
                ('expected_headers', models.JSONField(blank=True, default=dict)),
                ('expected_schema', models.JSONField(blank=True, default=dict)),
                ('request_headers', models.JSONField(blank=True, default=dict)),
                ('request_body', models.JSONField(blank=True, default=dict)),
                ('enabled', models.BooleanField(default=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('last_status', models.CharField(blank=True, max_length=20, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization')),
            ],
            options={
                'db_table': 'api_checks_target',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='APICheckResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('slow', 'Slow'), ('error', 'Error')], max_length=20)),
                ('http_status', models.IntegerField(blank=True, null=True)),
                ('response_time_ms', models.FloatField(blank=True, null=True)),
                ('json_valid', models.BooleanField(blank=True, null=True)),
                ('schema_valid', models.BooleanField(blank=True, null=True)),
                ('headers_valid', models.BooleanField(blank=True, null=True)),
                ('response_headers', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('checked_at', models.DateTimeField()),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='api_checks.apichecktarget')),
            ],
            options={
                'db_table': 'api_checks_result',
                'ordering': ['-checked_at'],
                'indexes': [models.Index(fields=['target', '-checked_at'], name='api_checks__target__3a7364_idx'), models.Index(fields=['status'], name='api_checks__status_ff1be0_idx')],
            },
        ),
    ]
