# Generated by Django 5.1.15 on 2026-08-09 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_checks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apichecktarget',
            name='check_interval',
            field=models.IntegerField(default=60),
        ),
    ]
