# Generated by Django 5.1.15 on 2026-09-03 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_checks', '0002_apichecktarget_check_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='apichecktarget',
            name='last_http_status',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apichecktarget',
            name='last_response_time_ms',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apichecktarget',
            name='method',
            field=models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE'), ('HEAD', 'HEAD')], default='GET', max_length=10),
        ),
    ]
