# Generated by Django 5.1.15 on 2026-08-08 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssl_monitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sslcertificate',
            name='san_domains',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='sslcertificate',
            name='tls_version',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
