# Generated by Django 5.1.15 on 2026-09-03 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssl_monitor', '0002_sslcertificate_san_domains_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sslcertificate',
            name='issued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sslcertificate',
            name='port',
            field=models.IntegerField(default=443),
        ),
        migrations.AddField(
            model_name='sslcertificate',
            name='security_grade',
            field=models.CharField(blank=True, default='A', max_length=10),
        ),
    ]
