# Generated by Django 5.1.15 on 2026-09-03 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='domaininfo',
            name='dnssec',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='domaininfo',
            name='is_locked',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='domaininfo',
            name='whois_server',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
