# Generated by Django 5.1.15 on 2026-07-28 15:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoringTarget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('target_type', models.CharField(choices=[('http', 'HTTP'), ('https', 'HTTPS'), ('tcp', 'TCP'), ('dns', 'DNS'), ('api', 'API'), ('ssl', 'SSL')], default='http', max_length=20)),
                ('endpoint', models.CharField(max_length=500)),
                ('interval', models.PositiveIntegerField(default=60, help_text='Check interval in seconds.')),
                ('enabled', models.BooleanField(default=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('last_status', models.CharField(blank=True, max_length=20, null=True)),
                ('last_latency', models.FloatField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization')),
            ],
            options={
                'db_table': 'monitoring_target',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MonitoringCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('up', 'Up'), ('down', 'Down'), ('slow', 'Slow'), ('error', 'Error')], max_length=20)),
                ('latency', models.FloatField(blank=True, null=True)),
                ('checked_at', models.DateTimeField()),
                ('details', models.JSONField(blank=True, default=dict)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='monitoring.monitoringtarget')),
            ],
            options={
                'db_table': 'monitoring_check',
                'ordering': ['-checked_at'],
                'indexes': [models.Index(fields=['target', '-checked_at'], name='monitoring__target__85aa03_idx'), models.Index(fields=['status'], name='monitoring__status_8e7ca1_idx')],
            },
        ),
    ]
