# Generated by Django 5.1.15 on 2026-08-08 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoringtarget',
            name='custom_headers',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='monitoringtarget',
            name='expected_status',
            field=models.PositiveIntegerField(default=200),
        ),
        migrations.AddField(
            model_name='monitoringtarget',
            name='http_method',
            field=models.CharField(default='GET', max_length=10),
        ),
        migrations.AddField(
            model_name='monitoringtarget',
            name='max_latency_ms',
            field=models.PositiveIntegerField(default=2000),
        ),
        migrations.AddField(
            model_name='monitoringtarget',
            name='request_body',
            field=models.TextField(blank=True, default=''),
        ),
    ]
