# Generated by Django 5.1.15 on 2026-09-04 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_monitoringtarget_tags_maintenancewindow'),
        ('users', '0003_team_contact_email_team_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoringtarget',
            name='owner_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitoring_targets', to='users.team'),
        ),
    ]
