# Generated by Django 5.1.15 on 2026-09-07 17:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0004_monitoringtarget_owner_team'),
        ('organizations', '0003_organization_alert_flapping_threshold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoringtarget',
            name='runner_type',
            field=models.CharField(choices=[('cloud', 'Sentinel Cloud'), ('agent', 'Private Agent')], default='cloud', help_text='Where the check is executed from.', max_length=20),
        ),
        migrations.CreateModel(
            name='AgentProbe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Human-readable probe identifier (e.g. Datacenter Santiago)', max_length=150)),
                ('token_hash', models.CharField(db_index=True, max_length=128, unique=True)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], default='offline', max_length=20)),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.CharField(blank=True, default='', max_length=45)),
                ('hostname', models.CharField(blank=True, default='', max_length=255)),
                ('version', models.CharField(default='1.0.0', max_length=20)),
                ('os_info', models.CharField(blank=True, default='', max_length=255)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization')),
            ],
            options={
                'db_table': 'monitoring_agent_probe',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='monitoringtarget',
            name='agent_probe',
            field=models.ForeignKey(blank=True, help_text='Assigned private probe if runner_type is agent.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_targets', to='monitoring.agentprobe'),
        ),
    ]
