from django.db import models

from common.models import BaseModel, OrganizationOwnedModel


class AlertRule(OrganizationOwnedModel):
    """Defines a rule that determines when to generate an alert.

    Each rule targets a specific monitoring type and evaluates
    a condition against a threshold value.
    """

    class TargetType(models.TextChoices):
        SSL = "ssl", "SSL"
        MONITORING = "monitoring", "Monitoring"
        DNS = "dns", "DNS"
        DOMAIN = "domain", "Domain"
        API_CHECK = "api_check", "API Check"
        SECURITY_HEADERS = "security_headers", "Security Headers"

    class ConditionType(models.TextChoices):
        SSL_EXPIRING = "ssl_expiring", "SSL Expiring"
        SSL_GRADE_BELOW = "ssl_grade_below", "SSL Grade Below"
        SSL_INVALID = "ssl_invalid", "SSL Invalid"
        UPTIME_BELOW = "uptime_below", "Uptime Below"
        STATUS_DOWN = "status_down", "Status Down"
        RESPONSE_TIME_ABOVE = "response_time_above", "Response Time Above"
        DNS_CHANGED = "dns_changed", "DNS Changed"
        DNS_LATENCY_ABOVE = "dns_latency_above", "DNS Latency Above"
        DOMAIN_EXPIRING = "domain_expiring", "Domain Expiring"
        DOMAIN_UNLOCKED = "domain_unlocked", "Domain Unlocked"
        SECURITY_SCORE_BELOW = "security_score_below", "Security Score Below"
        SECURITY_LEAK_DETECTED = "security_leak_detected", "Security Leak Detected"
        API_CHECK_FAILED = "api_check_failed", "API Check Failed"
        API_LATENCY_ABOVE = "api_latency_above", "API Latency Above"

    class Severity(models.TextChoices):
        CRITICAL = "critical", "Critical"
        WARNING = "warning", "Warning"
        INFO = "info", "Info"

    name = models.CharField(max_length=255)
    target_type = models.CharField(
        max_length=20,
        choices=TargetType.choices,
    )
    condition = models.CharField(
        max_length=40,
        choices=ConditionType.choices,
    )
    threshold = models.FloatField(
        default=0,
        help_text="Threshold value (days, percentage, milliseconds, etc.)",
    )
    severity = models.CharField(
        max_length=20,
        choices=Severity.choices,
        default=Severity.WARNING,
    )
    enabled = models.BooleanField(default=True)
    target_id = models.UUIDField(
        null=True,
        blank=True,
        help_text="Specific target ID or None for all targets of this type",
    )
    snoozed_until = models.DateTimeField(null=True, blank=True)
    cooldown_minutes = models.IntegerField(default=15)
    auto_resolve = models.BooleanField(default=True)
    last_triggered_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        ordering = ["-created_at"]
        db_table = "alerts_rule"

    def __str__(self):
        return f"{self.name} ({self.target_type} / {self.condition})"


class Alert(BaseModel):
    """An event generated by an alert rule.

    Represents a specific instance where a rule condition was met.
    """

    class Status(models.TextChoices):
        ACTIVE = "active", "Active"
        ACKNOWLEDGED = "acknowledged", "Acknowledged"
        RESOLVED = "resolved", "Resolved"

    organization = models.ForeignKey(
        "organizations.Organization",
        on_delete=models.CASCADE,
        related_name="alerts",
    )
    rule = models.ForeignKey(
        AlertRule,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="alerts",
    )
    title = models.CharField(max_length=500)
    message = models.TextField()
    severity = models.CharField(
        max_length=20,
        choices=AlertRule.Severity.choices,
    )
    status = models.CharField(
        max_length=20,
        choices=Status.choices,
        default=Status.ACTIVE,
    )
    target_type = models.CharField(max_length=20, blank=True)
    target_id = models.UUIDField(null=True, blank=True)
    occurrence_count = models.IntegerField(default=1)
    last_seen_at = models.DateTimeField(auto_now=True)
    is_flapping = models.BooleanField(default=False)
    flapping_count = models.IntegerField(default=0)
    snoozed_until = models.DateTimeField(null=True, blank=True)
    auto_resolved = models.BooleanField(default=False)
    metadata = models.JSONField(default=dict, blank=True)
    triggered_at = models.DateTimeField(auto_now_add=True)
    resolved_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        ordering = ["-triggered_at"]
        db_table = "alerts_alert"
        indexes = [
            models.Index(fields=["organization", "-triggered_at"]),
            models.Index(fields=["status"]),
            models.Index(fields=["severity"]),
            models.Index(fields=["target_type", "target_id"]),
        ]

    def __str__(self):
        return f"{self.title} ({self.severity} / {self.status})"