# Generated by Django 5.1.15 on 2026-08-09 02:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledMaintenance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization')),
            ],
            options={
                'db_table': 'status_page_maintenance',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='StatusPageConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(default='Servicios de la Empresa', max_length=255)),
                ('slug', models.CharField(db_index=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='Estado de disponibilidad y rendimiento de nuestros servicios en tiempo real.')),
                ('logo_url', models.CharField(blank=True, default='', max_length=1000)),
                ('is_public', models.BooleanField(default=True)),
                ('support_email', models.EmailField(blank=True, default='', max_length=254)),
                ('monitored_targets', models.JSONField(blank=True, default=list, help_text='List of target IDs to include on the status page')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization')),
            ],
            options={
                'db_table': 'status_page_config',
                'ordering': ['-created_at'],
            },
        ),
    ]
