# Generated by Django 5.1.15 on 2026-09-04 15:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_invitationtoken'),
        ('status_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statuspageconfig',
            name='announcement_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='statuspageconfig',
            name='announcement_type',
            field=models.CharField(choices=[('info', 'Informativo'), ('warning', 'Advertencia'), ('critical', 'Crítico')], default='info', max_length=20),
        ),
        migrations.AddField(
            model_name='statuspageconfig',
            name='component_settings',
            field=models.JSONField(blank=True, default=list, help_text='Detailed config of published components, categories, custom names, and visibility'),
        ),
        migrations.AddField(
            model_name='statuspageconfig',
            name='custom_announcement',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='statuspageconfig',
            name='show_latency_24h',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='statuspageconfig',
            name='show_uptime_pct',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='statuspageconfig',
            name='website_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.CreateModel(
            name='MaintenanceUpdate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('status', models.CharField(default='scheduled', max_length=20)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('maintenance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='status_page.scheduledmaintenance')),
            ],
            options={
                'db_table': 'status_page_maintenance_update',
                'ordering': ['-posted_at'],
            },
        ),
        migrations.CreateModel(
            name='StatusPageSubscriber',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization')),
                ('status_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='status_page.statuspageconfig')),
            ],
            options={
                'db_table': 'status_page_subscriber',
                'ordering': ['-created_at'],
                'unique_together': {('status_page', 'email')},
            },
        ),
    ]
