# Generated by Django 5.1.15 on 2026-09-04 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status_page', '0002_statuspageconfig_announcement_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledmaintenance',
            name='status_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='status_page.statuspageconfig'),
        ),
        migrations.AddField(
            model_name='statuspageconfig',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
