# Generated by Django 5.1.15 on 2026-07-28 15:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('user_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('user_email', models.CharField(blank=True, max_length=255)),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('config_change', 'Config Change'), ('alert_acknowledged', 'Alert Acknowledged'), ('alert_resolved', 'Alert Resolved'), ('incident_created', 'Incident Created'), ('incident_status_changed', 'Incident Status Changed'), ('incident_resolved', 'Incident Resolved'), ('incident_closed', 'Incident Closed'), ('role_assigned', 'Role Assigned'), ('role_removed', 'Role Removed'), ('notification_sent', 'Notification Sent'), ('report_generated', 'Report Generated')], max_length=50)),
                ('module', models.CharField(max_length=50)),
                ('result', models.CharField(choices=[('success', 'Success'), ('failure', 'Failure')], default='success', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'audit_log',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['organization_id', '-timestamp'], name='audit_log_organiz_65d8eb_idx'), models.Index(fields=['action'], name='audit_log_action_b32d4d_idx'), models.Index(fields=['module'], name='audit_log_module_24532b_idx'), models.Index(fields=['user_id'], name='audit_log_user_id_4dac76_idx')],
            },
        ),
    ]
